base_url = 'https://loremdipso.com/'
default_language = "en"
title = 'Welcome weary traveler'
theme = 'slender'
output_dir = './temp'

# A list of glob patterns specifying asset files to ignore when the content
# directory is processed. Defaults to none, which means that all asset files are
# copied over to the `public` directory.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*", "**/build_folder"]
ignored_content = []

generate_feed = true
compile_sass = true
minify_html = true
feed_filename = "rss.xml"
feed_limit = 10
build_search_index = false

# The taxonomies to be rendered for the site and their configuration of the default languages
taxonomies = [
    {name = "tags"},
    {name = "author"},
]


[markdown]
highlight_code = true

# A list of directories used to search for additional `.sublime-syntax` and `.tmTheme` files.
extra_syntaxes_and_themes = []

# The theme to use for code highlighting.
# See below for list of allowed values.
highlight_theme = "charcoal"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = false

# Configuration of the link checker.
[link_checker]
# Skip link checking for external URLs that start with these prefixes
skip_prefixes = [
    "http://[2001:db8::]/",
]

# Skip anchor checking for external URLs that start with these prefixes
skip_anchor_prefixes = [
    # "https://caniuse.com/",
]

# Treat internal link problems as either "error" or "warn", default is "error"
internal_level = "error"

# Treat external link problems as either "error" or "warn", default is "error"
external_level = "error"

# Various slugification strategies, see below for details
# Defaults to everything being a slug
[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the path of the page/section in the index
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true
# At which character to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
truncate_content_length = 100

[extra.author]
    name = "Michael Adams"
    job_title = "Software Engineer"
    profile_pic_url = "images/profile_pic.jpg"

[extra.strings]
    home = "Home"
    archives = "Posts"
    not_found = "Sorry, I couldn't find that page :/"
    copy = "Copy"
    table_of_contents = "Contents"
    next = "Up next"
    previous = "Previously"

    # Resume strings
    resume = "Resume"
    email = "Email"
    mobile = "Mobile"
    experience = "Experience"
    education = "Education"
    company = "Company"
    team = "Team"


[extra.params]
    dateform        = "%b %d, %Y"
    dateform_short  = "%b %d"

[[extra.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/loremdipso/"

[[extra.social]]
    name = "github"
    url = "https://github.com/loremdipso"

[[extra.menus]]
    name = "About"
    type = "self.html"
    url = "/"

# [[extra.menus.main]]
# 	name = "Projects"
# 	url = "/projects/"

[[extra.menus]]
    name = "Posts"
    url = "/posts/"

[[extra.menus]]
    name = "Resume"
    url = "/resume/"

# Resume
[extra.resume.contact]
    email = "mtadams42@gmail.com"

[[extra.resume.educations]]
    degree = "B.S. in Computer Science (cont'd)"
    period_start = "2011"
    period_end = "2014"
    description = "University of Tennessee, Knoxville"
    extra = "Member of the programming team for two years and then captain for one"
    website = "https://www.utk.edu/"

[[extra.resume.educations]]
    degree = "B.S. in Computer Science"
    period_start = "2010"
    period_end = "2011"
    description = "Tennessee Tech, Cookeville"
    website = "https://www.tntech.edu/"

[[extra.resume.skills]]
    name = "Agile"
    level = 99
[[extra.resume.skills]]
    name = "UX"
    level = 99
[[extra.resume.skills]]
    name = "C#"
    level = 99
[[extra.resume.skills]]
    name = "Java"
    level = 70
[[extra.resume.skills]]
    name = "HTML5"
    level = 99
[[extra.resume.skills]]
    name = "CSS 3"
    level = 95
[[extra.resume.skills]]
    name = "JavaScript"
    level = 95
[[extra.resume.skills]]
    name = "TypeScript"
    level = 95

[[extra.resume.experiences]]
    [extra.resume.experiences.company]
        name = "Google"
        website = "https://www.google.com"
        job_title = "Software Engineer"
        period_start = "Feb 2021"
        period_end = "Present"

        [[extra.resume.experiences.company.teams]]
            name = "Chat.Next"
            role = "Tech Lead"
            period_start = "Mar 2022"
            period_end = "Present"
            projects = [
                "Led the Google Cloud chat support product."
            ]

        [[extra.resume.experiences.company.teams]]
            name = "Cross Product Portal"
            role = "Software Engineer"
            period_start = "Feb 2021"
            period_end = "Mar 2022"
            projects = [
                "Launched the next-generation Google Cloud support platform."
            ]

[[extra.resume.experiences]]
    [extra.resume.experiences.company]
        name = "Epic"
        description = "Electronic Health Record system with over 190 million patients worldwide"
        website = "https://www.epic.com"
        job_title = "Software Developer"
        period_start = "June 2014"
        period_end = "Aug 2020"

        [[extra.resume.experiences.company.teams]]
            name = "ICU"
            role = "SD"
            period_start = "Jan 2020"
            period_end = "Aug 2020"
            projects = [
                "Designed and implemented the infrastructure that allows for easy integration of any video vendor's product."
                #"Created the infrastructure that allows generically integrating any video vendor's product with Epic's remote monitoring application. Previously these integrations had to be done manually and were thus extremely cost prohibitive."
            ]

        [[extra.resume.experiences.company.teams]]
            name = "Special Projects (aka Skunkworks)"
            role = "SD"
            # description: Task force that meant to advance framework and improve developer retention
            period_start = "Jan 2019"
            period_end = "Dec 2019"
            projects = [
                "Improved developer experience. Initiaties include: hot reloading, improving integration with an antiquated version control system, reducing boilerplate for new views, and improving fleet-wide performance via heavy use of immutable objects."
            # "Updated the web framework to support something akin to \"hot reloading,\" whereby developers would be able to see their UI changes in near realtime.",
            # "Improved Epic's integration with version control tools, saving time and reducing user error.",
            # could take out
            # "Obviated the need for two ASP.NET-specific files for all new projects, making development simpler and easier to port to other platforms.",
            # "Rewrote key parts of the core web framework to be immutable, dramatically improving performance.",
            # "Helped introduce React Functional Components to the existing architecture, which has helped foster increased reusability of components and, anecdotally, developer satisfaction.",
            ]

        [[extra.resume.experiences.company.teams]]
            name = "Social Care"
            role = "SD"
            period_start = "Jan 2018"
            period_end = "Apr 2018"
            projects = [
                "Created an interactive graphic of a patient's support network."
                # "Created an interactive graphic of a patient's support network. It's being used today to ensure patients are properly cared for ouside of the medical setting."
            ]

        [[extra.resume.experiences.positions.teams]]
            name = "Telehealth"
            role = "SD"
            period_start = "May 2017"
            period_end = "Dec 2018"
            projects = [
                "Lead architect on flagship product that allows for organizations to pool resources for virtual care."
                # "Lead architect on flagship product that allows for organizations to pool resources for virtual care. This improved availability of these services, reduced patient wait times, and reduced unnecessary usage of in-person facilities."
            ]

        [[extra.resume.experiences.company.teams]]
            name = "Endocrinology"
            role = "SD"
            period_start = "Nov 2016"
            period_end = "Apr 2017"
            projects = [
                "Part of small team that pioneered Epic's first Endocrinology module."
                # - "Part of small team that pioneered Epic's first Endocrinology module: a tool that standardized recording and displaying insulin instructions."
            ]

        [[extra.resume.experiences.company.teams]]
            name = "MyChart"
            role = "SD"
            description = "Team that builds the website patients use to connect to their healthcare organization"
            period_start = "Jan 2016"
            period_end = "Aug 2016"
            projects = [
                "Improved performance of graphing infrastructure."
                # "Improved performance of graphing infrastructure by ~25%."
            ]

