baseURL = 'https://loremdipso.com/'
languageCode = 'en'
defaultContentLanguage = "en"
title = 'Welcome weary traveler'
theme = 'slender'
numFeed = 10 # number of items in feed
publishDir = './docs'

[markup.goldmark.renderer]
	unsafe = true


[markup.highlight]
	# The below is pygmentsOptions
	codeFences = true
	guessSyntax = true
	hl_Lines = ""
	tabWidth = 2
	noClasses = false
	#lineNoStart = 1
	#lineNos = true
	#lineNumbersInTable = true

[author]
	name = "Michael Adams"
	job_title = "Software Engineer"
	profile_pic_url = "images/profile_pic.jpg"

[params]
	dateform        = "Jan 2, 2006"
	dateformShort   = "Jan 2"
	dateformNum     = "2006-01-02"
	dateformNumTime = "2006-01-02 12:04 -0700"
	# 2022-01-08T10:49:55-07:00

[[params.social]]
	name = "linkedin"
	url = "https://www.linkedin.com/in/loremdipso/"

[[params.social]]
	name = "github"
	url = "https://github.com/loremdipso"

[menu]
	[[menu.main]]
		name = "About"
		type = "self.html"
		url = "/"

	# [[menu.main]]
	# 	name = "Projects"
	# 	url = "/projects/"

	[[menu.main]]
		name = "Posts"
		url = "/posts/"

	[[menu.main]]
		name = "Resume"
		url = "/resume/"
