[metadata]
name = "Michael Adams"
page_title = "Michael Adams Resume"
email = "mtadams42@gmail.com"

[[data.sections]]
title = "EXPERIENCE"
experiences = []

[[data.sections.organizations]]
title = "Google"
short_description = "Customer Support Software"
long_description = ""
url = "https://google.com"
timeframe = "Feb 2021 - Oct 2024"

[[data.sections.organizations.teams]]
title = "Tech Lead for Chat.Next"
timeframe = "Mar 2022 - Nov 2024"
experiences = ["Designer and lead engineer for the Generative AI and live chat frontend.", "Led the small team behind Google Cloud's chat support product."]

[[data.sections.organizations.teams]]
title = "Software Engineer on Cross Product Portal"
timeframe = "Feb 2021 - Mar 2022"
experiences = ["Launched the next-generation Google Cloud support platform."]

[[data.sections.organizations]]
title = "Epic"
short_description = "Healthcare Software"
long_description = ""
url = "https://epic.com"
timeframe = "June 2014 - Aug 2020"

[[data.sections.organizations.teams]]
title = "ICU"
timeframe = "Jan 2020 - Aug 2020"
experiences = ["Created the infrastructure that facilitated seamless integration of new video vendors, reducing costs for both video vendors and hospitals."]

[[data.sections.organizations.teams]]
title = "Special Projects (aka Skunkworks)"
timeframe = "Jan 2019 - Dec 2019"
experiences = ["Improved developer experience. This included hot reloading, improving integration with an antiquated version control system, reducing boilerplate for new views, and improving fleet-wide performance via heavy use of immutable objects."]

[[data.sections.organizations.teams]]
title = "Social Care"
timeframe = "Jan 2018 - Apr 2018"
experiences = ["Created an interactive graphic displaying a patient's support network."]

[[data.sections.organizations.teams]]
title = "Telehealth"
timeframe = "May 2017 - Dec 2018"
experiences = ["Lead architect on flagship product that allows for organizations to pool resources for virtual care."]

[[data.sections.organizations.teams]]
title = "Endocrinology"
timeframe = "Nov 2016 - Apr 2017"
experiences = ["Principal engineer on Epic's first endocrinology module."]

[[data.sections.organizations.teams]]
title = "MyChart"
timeframe = "Jan 2016 - Aug 2016"
experiences = ["Improved the performance of the graphing infrastructure."]

[[data.sections]]
title = "EDUCATION"
experiences = []

[[data.sections.organizations]]
title = "University of Tennessee, Knoxville"
short_description = ""
long_description = ""
url = "https://utk.edu/"
timeframe = ""

[[data.sections.organizations.teams]]
title = "B.S. in Computer Science, 2014"
timeframe = ""
experiences = ["Programming team member for two years and team captain for one.", "Served as a Teaching Assistant for the Intro to Computer Science course."]
